version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgres-postgis
    restart: always
    environment:
      POSTGRES_USER: cwa24user
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: cwa24_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: